version: '3'

services:
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

    restart: unless-stopped
    networks:
      - test_network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: Redis_Practice
    ports:
      - "3307:3306"
    networks:
      - test_network

  spring-all-in-one:
    container_name: spring-all-in-one
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PW: 1234
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/Redis_Practice?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789

    depends_on:
      - redis
      - mysql
    networks:
      - test_network
    restart: unless-stopped

networks:
  test_network: